# Generated by Django 5.0.1 on 2026-03-01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname_type', models.CharField(max_length=6)),
                ('hostname', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100, null=True)),
                ('is_alert_enabled', models.BooleanField(default=False)),
                ('is_monitor_enabled', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=10)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [
                    models.Index(fields=['user', 'created'], name='apps_hostna_user_id_2614d5_idx'),
                    models.Index(fields=['hostname'], name='apps_hostna_hostnam_2f998b_idx'),
                    models.Index(fields=['status'], name='apps_hostna_status_96b196_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('user', 'hostname'), name='unique_hostname_per_user'),
                ],
            },
        ),
        migrations.CreateModel(
            name='CheckHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField(null=True)),
                ('status', models.CharField(max_length=9)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hostname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostname.hostname')),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [
                    models.Index(fields=['hostname', 'status'], name='apps_hostna_hostnam_5f6597_idx'),
                    models.Index(fields=['created'], name='apps_hostna_created_838da1_idx'),
                ],
            },
        ),
    ]
